spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/zadanie
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver